// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proxy/reflex/account.proto

package reflex

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	"github.com/xtls/xray-core/common/errors"
	"github.com/xtls/xray-core/common/protocol"
	"github.com/xtls/xray-core/common/uuid"
	"google.golang.org/protobuf/proto"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Policy for traffic morphing (e.g., "mimic-http2-api", "mimic-youtube")
	Policy        string `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_reflex_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

var File_proxy_reflex_account_proto protoreflect.FileDescriptor

const file_proxy_reflex_account_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/reflex/account.proto\x12\x11xray.proxy.reflex\"1\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06policy\x18\x02 \x01(\tR\x06policyBU\n" +
	"\x15com.xray.proxy.reflexP\x01Z&github.com/xtls/xray-core/proxy/reflex\xaa\x02\x11Xray.Proxy.Reflexb\x06proto3"

var (
	file_proxy_reflex_account_proto_rawDescOnce sync.Once
	file_proxy_reflex_account_proto_rawDescData []byte
)

func file_proxy_reflex_account_proto_rawDescGZIP() []byte {
	file_proxy_reflex_account_proto_rawDescOnce.Do(func() {
		file_proxy_reflex_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_reflex_account_proto_rawDesc), len(file_proxy_reflex_account_proto_rawDesc)))
	})
	return file_proxy_reflex_account_proto_rawDescData
}

var file_proxy_reflex_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_reflex_account_proto_goTypes = []any{
	(*Account)(nil), // 0: xray.proxy.reflex.Account
}
var file_proxy_reflex_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_reflex_account_proto_init() }
func file_proxy_reflex_account_proto_init() {
	if File_proxy_reflex_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_reflex_account_proto_rawDesc), len(file_proxy_reflex_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_reflex_account_proto_goTypes,
		DependencyIndexes: file_proxy_reflex_account_proto_depIdxs,
		MessageInfos:      file_proxy_reflex_account_proto_msgTypes,
	}.Build()
	File_proxy_reflex_account_proto = out.File
	file_proxy_reflex_account_proto_goTypes = nil
	file_proxy_reflex_account_proto_depIdxs = nil
}

// AsAccount implements protocol.Account.AsAccount().
func (a *Account) AsAccount() (protocol.Account, error) {
	id, err := uuid.ParseString(a.Id)
	if err != nil {
		return nil, errors.New("failed to parse ID: ", err)
	}
	return &MemoryAccount{
		ID:     protocol.NewID(id),
		Policy: a.Policy,
	}, nil
}

// MemoryAccount is an in-memory form of Reflex account.
type MemoryAccount struct {
	ID     *protocol.ID
	Policy string
}

// Equals implements protocol.Account.Equals().
func (a *MemoryAccount) Equals(account protocol.Account) bool {
	reflexAccount, ok := account.(*MemoryAccount)
	if !ok {
		return false
	}
	return a.ID.Equals(reflexAccount.ID)
}

// ToProto converts MemoryAccount to Account (implements proto.Message)
func (a *MemoryAccount) ToProto() proto.Message {
	return &Account{
		Id:     a.ID.String(),
		Policy: a.Policy,
	}
}
