// Code generated by protoc-gen-go. DO NOT EDIT.
package reflex

import (
    protoreflect "google.golang.org/protobuf/reflect/protoreflect"
    protoimpl "google.golang.org/protobuf/runtime/protoimpl"
    reflect "reflect"
    sync "sync"
)

const (
    _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
    _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields
    Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
    Policy string `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
}
func (x *User) Reset() { *x = User{} }
func (*User) ProtoMessage() {}
func (x *User) ProtoReflect() protoreflect.Message {
    mi := &file_config_proto_msgTypes[0]
    if protoimpl.UnsafeEnabled && x != nil { return ms.MessageOf(x) }
    return mi.MessageOf(x)
}
func (x *User) GetId() string { if x != nil { return x.Id }; return "" }
func (x *User) GetPolicy() string { if x != nil { return x.Policy }; return "" }

type Account struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields
    Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}
func (x *Account) Reset() { *x = Account{} }
func (*Account) ProtoMessage() {}
func (x *Account) ProtoReflect() protoreflect.Message {
    mi := &file_config_proto_msgTypes[1]
    if protoimpl.UnsafeEnabled && x != nil { return ms.MessageOf(x) }
    return mi.MessageOf(x)
}
func (x *Account) GetId() string { if x != nil { return x.Id }; return "" }

type Fallback struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields
    Dest uint32 `protobuf:"varint,1,opt,name=dest,proto3" json:"dest,omitempty"`
}
func (x *Fallback) Reset() { *x = Fallback{} }
func (*Fallback) ProtoMessage() {}
func (x *Fallback) ProtoReflect() protoreflect.Message {
    mi := &file_config_proto_msgTypes[2]
    if protoimpl.UnsafeEnabled && x != nil { return ms.MessageOf(x) }
    return mi.MessageOf(x)
}
func (x *Fallback) GetDest() uint32 { if x != nil { return x.Dest }; return 0 }

type InboundConfig struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields
    Clients  []*User   `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
    Fallback *Fallback `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
}
func (x *InboundConfig) Reset() { *x = InboundConfig{} }
func (*InboundConfig) ProtoMessage() {}
func (x *InboundConfig) ProtoReflect() protoreflect.Message {
    mi := &file_config_proto_msgTypes[3]
    if protoimpl.UnsafeEnabled && x != nil { return ms.MessageOf(x) }
    return mi.MessageOf(x)
}
func (x *InboundConfig) GetClients() []*User { if x != nil { return x.Clients }; return nil }
func (x *InboundConfig) GetFallback() *Fallback { if x != nil { return x.Fallback }; return nil }

type OutboundConfig struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields
    Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
    Port    uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
    Id      string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}
func (x *OutboundConfig) Reset() { *x = OutboundConfig{} }
func (*OutboundConfig) ProtoMessage() {}
func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
    mi := &file_config_proto_msgTypes[4]
    if protoimpl.UnsafeEnabled && x != nil { return ms.MessageOf(x) }
    return mi.MessageOf(x)
}

var File_config_proto protoreflect.FileDescriptor
var file_config_proto_rawDesc = []byte{
    0x0a, 0x19, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x78, 0x2f, 0x63,
    0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x66,
    0x6c, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0x2e, 0x0a, 0x04, 0x55, 0x73, 0x65,
    0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
    0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
    0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_proto_goTypes = []interface{}{
    (*User)(nil), (*Account)(nil), (*Fallback)(nil), (*InboundConfig)(nil), (*OutboundConfig)(nil),
}
var file_config_proto_depIdxs = []int32{0, 2, 2, 2, 2, 2, 0}
func init() {
    type x struct{}
    out := protoimpl.TypeBuilder{
        File: protoimpl.DescBuilder{
            GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
            RawDescriptor: file_config_proto_rawDesc,
            NumEnums: 0, NumMessages: 5, NumExtensions: 0, NumServices: 0,
        },
        GoTypes: file_config_proto_goTypes,
        DependencyIndexes: file_config_proto_depIdxs,
        MessageInfos: file_config_proto_msgTypes,
    }.Build()
    File_config_proto = out.File
    file_config_proto_rawDesc = nil
    file_config_proto_goTypes = nil
    file_config_proto_depIdxs = nil
}
