// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proxy/reflex/config.proto

package reflex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Policy        string                 `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proxy_reflex_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_reflex_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*User                `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Fallback      *Fallback              `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	Ech           *ECHSettings           `protobuf:"bytes,3,opt,name=ech,proto3" json:"ech,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
	mi := &file_proxy_reflex_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundConfig.ProtoReflect.Descriptor instead.
func (*InboundConfig) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{2}
}

func (x *InboundConfig) GetClients() []*User {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *InboundConfig) GetFallback() *Fallback {
	if x != nil {
		return x.Fallback
	}
	return nil
}

func (x *InboundConfig) GetEch() *ECHSettings {
	if x != nil {
		return x.Ech
	}
	return nil
}

type Fallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dest          uint32                 `protobuf:"varint,1,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fallback) Reset() {
	*x = Fallback{}
	mi := &file_proxy_reflex_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fallback) ProtoMessage() {}

func (x *Fallback) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fallback.ProtoReflect.Descriptor instead.
func (*Fallback) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{3}
}

func (x *Fallback) GetDest() uint32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

type OutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Policy        string                 `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	Ech           *ECHSettings           `protobuf:"bytes,5,opt,name=ech,proto3" json:"ech,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundConfig) Reset() {
	*x = OutboundConfig{}
	mi := &file_proxy_reflex_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundConfig) ProtoMessage() {}

func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundConfig.ProtoReflect.Descriptor instead.
func (*OutboundConfig) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{4}
}

func (x *OutboundConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OutboundConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *OutboundConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboundConfig) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *OutboundConfig) GetEch() *ECHSettings {
	if x != nil {
		return x.Ech
	}
	return nil
}

type ECHSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PublicName    string                 `protobuf:"bytes,2,opt,name=public_name,json=publicName,proto3" json:"public_name,omitempty"`
	CertFile      string                 `protobuf:"bytes,3,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,4,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	ServerName    string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Insecure      bool                   `protobuf:"varint,6,opt,name=insecure,proto3" json:"insecure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECHSettings) Reset() {
	*x = ECHSettings{}
	mi := &file_proxy_reflex_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECHSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECHSettings) ProtoMessage() {}

func (x *ECHSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECHSettings.ProtoReflect.Descriptor instead.
func (*ECHSettings) Descriptor() ([]byte, []int) {
	return file_proxy_reflex_config_proto_rawDescGZIP(), []int{5}
}

func (x *ECHSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ECHSettings) GetPublicName() string {
	if x != nil {
		return x.PublicName
	}
	return ""
}

func (x *ECHSettings) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ECHSettings) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ECHSettings) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ECHSettings) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

var File_proxy_reflex_config_proto protoreflect.FileDescriptor

const file_proxy_reflex_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/reflex/config.proto\x12\freflex.proxy\".\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06policy\x18\x02 \x01(\tR\x06policy\"\x19\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9e\x01\n" +
	"\rInboundConfig\x12,\n" +
	"\aclients\x18\x01 \x03(\v2\x12.reflex.proxy.UserR\aclients\x122\n" +
	"\bfallback\x18\x02 \x01(\v2\x16.reflex.proxy.FallbackR\bfallback\x12+\n" +
	"\x03ech\x18\x03 \x01(\v2\x19.reflex.proxy.ECHSettingsR\x03ech\"\x1e\n" +
	"\bFallback\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\rR\x04dest\"\x93\x01\n" +
	"\x0eOutboundConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\x12+\n" +
	"\x03ech\x18\x05 \x01(\v2\x19.reflex.proxy.ECHSettingsR\x03ech\"\xbd\x01\n" +
	"\vECHSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vpublic_name\x18\x02 \x01(\tR\n" +
	"publicName\x12\x1b\n" +
	"\tcert_file\x18\x03 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x04 \x01(\tR\akeyFile\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x12\x1a\n" +
	"\binsecure\x18\x06 \x01(\bR\binsecureB(Z&github.com/xtls/xray-core/proxy/reflexb\x06proto3"

var (
	file_proxy_reflex_config_proto_rawDescOnce sync.Once
	file_proxy_reflex_config_proto_rawDescData []byte
)

func file_proxy_reflex_config_proto_rawDescGZIP() []byte {
	file_proxy_reflex_config_proto_rawDescOnce.Do(func() {
		file_proxy_reflex_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_reflex_config_proto_rawDesc), len(file_proxy_reflex_config_proto_rawDesc)))
	})
	return file_proxy_reflex_config_proto_rawDescData
}

var file_proxy_reflex_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proxy_reflex_config_proto_goTypes = []any{
	(*User)(nil),           // 0: reflex.proxy.User
	(*Account)(nil),        // 1: reflex.proxy.Account
	(*InboundConfig)(nil),  // 2: reflex.proxy.InboundConfig
	(*Fallback)(nil),       // 3: reflex.proxy.Fallback
	(*OutboundConfig)(nil), // 4: reflex.proxy.OutboundConfig
	(*ECHSettings)(nil),    // 5: reflex.proxy.ECHSettings
}
var file_proxy_reflex_config_proto_depIdxs = []int32{
	0, // 0: reflex.proxy.InboundConfig.clients:type_name -> reflex.proxy.User
	3, // 1: reflex.proxy.InboundConfig.fallback:type_name -> reflex.proxy.Fallback
	5, // 2: reflex.proxy.InboundConfig.ech:type_name -> reflex.proxy.ECHSettings
	5, // 3: reflex.proxy.OutboundConfig.ech:type_name -> reflex.proxy.ECHSettings
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proxy_reflex_config_proto_init() }
func file_proxy_reflex_config_proto_init() {
	if File_proxy_reflex_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_reflex_config_proto_rawDesc), len(file_proxy_reflex_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_reflex_config_proto_goTypes,
		DependencyIndexes: file_proxy_reflex_config_proto_depIdxs,
		MessageInfos:      file_proxy_reflex_config_proto_msgTypes,
	}.Build()
	File_proxy_reflex_config_proto = out.File
	file_proxy_reflex_config_proto_goTypes = nil
	file_proxy_reflex_config_proto_depIdxs = nil
}
