// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version. Please regenerate with protoc for production use.
// source: proxy/reflex/config.proto

package reflex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Policy string `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	if ms.LoadMessageInfo() == nil {
		ms.StoreMessageInfo(mi)
	}
	return ms
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	if ms.LoadMessageInfo() == nil {
		ms.StoreMessageInfo(mi)
	}
	return ms
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Fallback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest uint32 `protobuf:"varint,1,opt,name=dest,proto3" json:"dest,omitempty"`
}

func (x *Fallback) Reset() {
	*x = Fallback{}
}

func (x *Fallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fallback) ProtoMessage() {}

func (x *Fallback) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	if ms.LoadMessageInfo() == nil {
		ms.StoreMessageInfo(mi)
	}
	return ms
}

func (x *Fallback) GetDest() uint32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

type InboundConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clients  []*User   `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Fallback *Fallback `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	if ms.LoadMessageInfo() == nil {
		ms.StoreMessageInfo(mi)
	}
	return ms
}

func (x *InboundConfig) GetClients() []*User {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *InboundConfig) GetFallback() *Fallback {
	if x != nil {
		return x.Fallback
	}
	return nil
}

type OutboundConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port    uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *OutboundConfig) Reset() {
	*x = OutboundConfig{}
}

func (x *OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundConfig) ProtoMessage() {}

func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_reflex_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	if ms.LoadMessageInfo() == nil {
		ms.StoreMessageInfo(mi)
	}
	return ms
}

func (x *OutboundConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OutboundConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *OutboundConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proxy_reflex_config_proto protoreflect.FileDescriptor

var (
	file_proxy_reflex_config_proto_rawDesc        = []byte{0x0a}
	file_proxy_reflex_config_proto_rawDescOnce    sync.Once
	file_proxy_reflex_config_proto_rawDescData    []byte
	file_proxy_reflex_config_proto_msgTypes       = make([]protoimpl.MessageInfo, 5)
	file_proxy_reflex_config_proto_goTypes       = []interface{}{
		(*User)(nil),          // 0: reflex.proxy.User
		(*Account)(nil),       // 1: reflex.proxy.Account
		(*Fallback)(nil),      // 2: reflex.proxy.Fallback
		(*InboundConfig)(nil), // 3: reflex.proxy.InboundConfig
		(*OutboundConfig)(nil), // 4: reflex.proxy.OutboundConfig
	}
	file_proxy_reflex_config_proto_depIdxs = []int32{
		0, // 0: reflex.proxy.InboundConfig.clients:type_name -> reflex.proxy.User
		2, // 1: reflex.proxy.InboundConfig.fallback:type_name -> reflex.proxy.Fallback
	}
)

func file_proxy_reflex_config_proto_rawDescGZIP() []byte {
	file_proxy_reflex_config_proto_rawDescOnce.Do(func() {
		file_proxy_reflex_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxy_reflex_config_proto_rawDescData)
	})
	return file_proxy_reflex_config_proto_rawDescData
}

func init() { file_proxy_reflex_config_proto_init() }
func file_proxy_reflex_config_proto_init() {
	if File_proxy_reflex_config_proto != nil {
		return
	}
	// Initialize message types
}

